# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end
config.vm.define :streama do |streama|
streama.vm.box = "bento/centos-7.9"
streama.vm.network :private_network, ip: "192.168.100.2"
servidor2.vm.provision "shell", path: "script.sh"
streama.vm.hostname = "streama"
end
config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7.9"
firewall.vm.network :public_network, ip: "192.168.1.50"
firewall.vm.network :private_network, ip: "192.168.100.3"
servidor2.vm.provision "shell", path: "script2.sh"
firewall.vm.hostname = "firewall"
end
end